/* Datos del recorrido Campus CESA. Cada `folder` es relativo a "../Registro fotografico/". */

const CAMPUS_INTRO = {
  eyebrow: 'Dirección de Infraestructura · Iniciativa Campus CESA',
  title: 'Campus CESA',
  subtitle: 'Un recorrido por la transformación de nuestros espacios',
  lead: 'La Iniciativa Campus CESA es el proyecto estratégico liderado por la Dirección de Infraestructura que materializa, a través de la transformación de los espacios físicos, la visión del Plan de Transformación del CESA. Cada intervención convierte la infraestructura en un habilitador del desarrollo institucional y de la experiencia de toda la comunidad CESA.',
  body: 'Esta iniciativa impulsa la modernización progresiva del campus mediante la renovación y creación de espacios flexibles, tecnológicos, sostenibles y centrados en las personas, capaces de acompañar la evolución del modelo educativo CESA for Life y fortalecer los pilares de innovación educativa, transformación organizacional, cultura y bienestar. Más que un conjunto de proyectos de infraestructura, Campus CESA constituye una estrategia de transformación integral hacia un modelo de Smart Campus, donde la arquitectura, la tecnología y el diseño trabajan de manera articulada para ofrecer experiencias de alto valor.',
};

const CAMPUS_STATS = [
  { value: '10', label: 'proyectos de infraestructura' },
  { value: '1.797 m²', label: 'modernizados en salones' },
  { value: '21', label: 'salones flexibles nuevos' },
  { value: '5', label: 'puntos de acceso inteligente' },
];

/**
 * structure:
 *  'phases'    -> imágenes dentro de <folder>/ANTES, /DESPUES, /DURANTE
 *  'flatFiles' -> archivos sueltos directamente en <folder>, un nombre por fase
 *  'gallery'   -> archivos sueltos sin distinción de fase (solo registro)
 */
const CAMPUS_SPACES = [
  {
    id: 'salones',
    pilar: 'Innovación Educativa · CESA for Life',
    title: 'Modernización de salones',
    summary: 'Modernizamos 1.797 m² con la creación de 21 salones flexibles: nueva alfombra acústica, iluminación LED, sillas móviles, puestos docentes flexibles y tomas eléctricas a nivel de piso.',
    full: [
      'Como parte de la Iniciativa Campus CESA, esta intervención responde al propósito de transformar la infraestructura física en un habilitador estratégico del Plan de Transformación. La modernización de los espacios académicos busca acompañar la evolución hacia un modelo de aprendizaje más flexible, colaborativo y apoyado en la tecnología.',
      'Se modernizaron 1.797 m² mediante la creación de 21 salones flexibles, incorporando nueva alfombra para mejorar el confort y el acondicionamiento acústico, iluminación LED de luz neutra, sillas individuales móviles que permiten adaptar rápidamente la distribución del aula y nuevos puestos docentes flexibles. Adicionalmente, se instalaron tomas eléctricas a nivel de piso que garantizan conectividad desde cualquier configuración del salón.',
      'La intervención se desarrolló de manera articulada con Tecnologías de la Información, renovando la infraestructura eléctrica y de datos para integrar cámaras de seguimiento para clases híbridas, micrófonos y sistemas audiovisuales, consolidando aulas preparadas para el aprendizaje activo y el modelo CESA for Life.',
    ],
    folder: '1. MODERNIZACIÓN SALONES',
    structure: 'phases',
    antes: [
      'antes.png',
      'Captura de pantalla 2026-07-30 074339.png',
      'Captura de pantalla 2026-07-30 073829.png',
      'Captura de pantalla 2026-07-30 073850.png',
      'Captura de pantalla 2026-07-30 073810.png',
    ],
    despues: [
      'despues.jpeg',
      'WhatsApp Image 2026-07-29 at 4.06.20 PM (1).jpeg',
      'WhatsApp Image 2026-07-29 at 4.06.20 PM (2).jpeg',
      'WhatsApp Image 2026-07-29 at 4.06.20 PM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.42 AM (4).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.42 AM (5).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.43 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.43 AM (2).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.43 AM (3).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.43 AM (4).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.43 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.03 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.05 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.05 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 8.58.27 AM.jpeg',
      'ChatGPT Image 31 jul 2026, 08_24_23 a.m..png',
      'ChatGPT Image 29 jul 2026, 03_57_20 p.m..png',
      'ChatGPT Image 29 jul 2026, 03_38_38 p.m..png',
      'ChatGPT Image 29 jul 2026, 03_41_15 p.m..png',
      'ChatGPT Image 29 jul 2026, 03_42_54 p.m..png',
    ],
  },
  {
    id: 'cafeteria-incolda',
    pilar: 'Cultura, Bienestar y Sostenibilidad',
    title: 'Cafetería Incolda',
    summary: 'Un nuevo punto de encuentro para colaboradores administrativos: diseño contemporáneo, materiales cálidos e iluminación arquitectónica que fortalecen la integración y el bienestar cotidiano.',
    full: [
      'La creación de la cafetería de Casa Incolda responde al propósito de consolidar espacios que favorezcan el bienestar, la interacción y la calidad de vida de los colaboradores administrativos, en coherencia con el Plan de Transformación y su enfoque en cultura, sostenibilidad y experiencia institucional.',
      'El proyecto incorporó un diseño contemporáneo con materiales cálidos, acabados de alta calidad, iluminación arquitectónica y una distribución funcional que mejora la comodidad, la circulación y el aprovechamiento del espacio.',
      'Con esta intervención, la cafetería se convierte en un punto de encuentro que trasciende su función de alimentación para aportar al bienestar cotidiano, la integración entre áreas y el sentido de pertenencia.',
    ],
    folder: 'CAFETERÍA INCOLDA',
    structure: 'phases',
    antes: [
      'Captura de pantalla 2026-07-30 072532.png',
      'Captura de pantalla 2026-07-30 072515.png',
    ],
    despues: [
      'Captura de pantalla 2026-05-08 104752.png',
      'Captura de pantalla 2026-05-08 105130.png',
    ],
    durante: [
      'WhatsApp Image 2026-07-30 at 7.51.31 AM (2).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.31 AM (3).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.31 AM (4).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.31 AM (5).jpeg',
    ],
  },
  {
    id: 'biblioteca',
    pilar: 'Innovación Educativa · Cultura y Bienestar',
    title: 'Modernización de alfombra – Casa Biblioteca',
    summary: 'Primer hito de la transformación de Casa Biblioteca en un Learning Commons: renovación total de la alfombra con colores y texturas que diferencian zonas de estudio, colaboración y permanencia.',
    full: [
      'La transformación de Casa Biblioteca representa uno de los proyectos estratégicos de la Iniciativa Campus CESA, orientado a evolucionar la biblioteca tradicional hacia un espacio de aprendizaje activo, colaboración e innovación. Actualmente se desarrolla un proceso de análisis, diagnóstico y mesas de diálogo con las diferentes áreas y usuarios.',
      'Como primer hito de esta transformación integral, se llevó a cabo la renovación total de la alfombra en todos los espacios de Casa Biblioteca, implementando una propuesta de diseño basada en la identidad y funcionalidad de cada ambiente. La selección de colores, texturas y patrones permitió diferenciar zonas de estudio, colaboración y permanencia.',
      'Esta renovación es la primera etapa de un proyecto de modernización mucho más amplio que contempla la redefinición de los espacios y nuevas áreas de aprendizaje, consolidando la biblioteca como un verdadero Learning Commons para el CESA.',
    ],
    folder: 'CAMBIO TAPETE BIBLIOTECA',
    structure: 'phases',
    antes: [
      'Anexo 3 - vista general antes.png',
      'WhatsApp Image 2026-07-30 at 7.51.37 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.38 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.38 AM (2).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.38 AM (3).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.38 AM (4).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.38 AM (5).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.38 AM (6).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.38 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.39 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.41 AM.jpeg',
    ],
    despues: [
      'Anexo 4 - vista general despues.png',
      'WhatsApp Image 2026-07-29 at 4.06.21 PM (1).jpeg',
      'WhatsApp Image 2026-07-29 at 4.06.21 PM (2).jpeg',
      'WhatsApp Image 2026-07-29 at 4.06.21 PM (3).jpeg',
      'WhatsApp Image 2026-07-29 at 4.06.21 PM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.47 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.50 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.51 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.51 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.59 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.00 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.00 AM (2).jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.00 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.01 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.52.03 AM.jpeg',
    ],
  },
  {
    id: 'cesa-contigo',
    pilar: 'Transformación Organizacional · Cultura y Bienestar',
    title: 'Adecuación "CESA Contigo"',
    summary: 'El nuevo Centro de Atención Integral 360 para estudiantes: nueva alfombra, iluminación LED, pintura y mobiliario ergonómico en un solo punto de acompañamiento académico, administrativo y tecnológico.',
    full: [
      'La creación de CESA Contigo, el nuevo Centro de Atención Integral 360 para estudiantes, responde al propósito de fortalecer la experiencia de la comunidad CESA mediante un modelo de atención más cercano, eficiente e integrado. Este espacio consolida en un solo punto la atención de procesos académicos, administrativos y tecnológicos.',
      'La intervención contempló nueva alfombra que mejora el confort y el acondicionamiento acústico; iluminación LED para ambientes más cálidos y eficientes; renovación de pintura y acabados; y nuevo mobiliario ergonómico diseñado para optimizar la atención personalizada.',
      'Con esta transformación, CESA Contigo se consolida como un espacio que integra infraestructura, servicio y experiencia, ofreciendo un entorno moderno, accesible y funcional para el acompañamiento integral de los estudiantes.',
    ],
    folder: '2.CESA CONTIGO',
    structure: 'phases',
    despues: [
      'ChatGPT Image 29 jul 2026, 03_22_35 p.m..png',
      'ChatGPT Image 29 jul 2026, 03_24_37 p.m..png',
      'Captura de pantalla 2026-07-29 151725.png',
    ],
  },
  {
    id: 'banos-auditorio',
    pilar: 'Cultura, Bienestar y Sostenibilidad',
    title: 'Modernización de baños del Auditorio',
    summary: 'Renovación integral de las baterías de baños del Auditorio de Casa CESA: nuevos acabados, divisiones en vidrio templado, mobiliario sanitario contemporáneo e iluminación decorativa.',
    full: [
      'La modernización de las baterías de baños del Auditorio de Casa CESA responde al propósito de fortalecer la calidad de los espacios que acompañan las principales actividades académicas, empresariales e institucionales del campus.',
      'La intervención contempló una renovación integral mediante nuevos acabados arquitectónicos, revestimientos de alta durabilidad, divisiones en vidrio templado, mobiliario sanitario contemporáneo, espejos, iluminación decorativa y accesorios. Asimismo, se adecuó el acceso exterior, integrando la intervención con la arquitectura patrimonial de Casa CESA.',
      'Con este proyecto, el CESA fortalece los pilares de Cultura, Bienestar y Sostenibilidad y Transformación Organizacional, ofreciendo servicios modernos que complementan la experiencia de quienes participan diariamente en actividades académicas y eventos institucionales.',
    ],
    folder: 'MOD BAÑOS AUDITORIO',
    structure: 'phases',
    antes: [
      'Captura de pantalla 2026-07-30 073246.png',
      'Captura de pantalla 2026-07-30 073257.png',
    ],
    despues: [
      'Captura de pantalla 2026-07-30 072946.png',
      'Captura de pantalla 2026-07-30 073040.png',
      'Captura de pantalla 2026-07-30 072935.png',
    ],
  },
  {
    id: 'hall-vargas',
    pilar: 'Cultura, Bienestar y Sostenibilidad',
    title: 'Modernización de hall y baños Casa Vargas',
    summary: 'El hall dejó de ser solo un espacio de circulación: mobiliario tipo coworking, zonas de descanso y vegetación, más baños modernizados con un baño accesible para movilidad reducida.',
    full: [
      'La transformación del hall y las baterías de baños de Casa Vargas responde al objetivo de consolidar espacios que promuevan el bienestar, la interacción, la inclusión y el desarrollo integral de la comunidad CESA.',
      'El hall dejó de ser únicamente un espacio de circulación para convertirse en un entorno de permanencia y encuentro, mediante la incorporación de mobiliario flexible tipo coworking, zonas de descanso y vegetación. La instalación de porcelanato de alto desempeño aportó una imagen contemporánea y mayor resistencia al alto tráfico.',
      'La modernización de las baterías de baños elevó la calidad de los servicios mediante nuevos acabados, revestimientos, iluminación decorativa, mobiliario, espejos y accesorios. La incorporación de un baño para personas con movilidad reducida garantiza un uso seguro, digno y autónomo.',
    ],
    folder: 'MOD HALL Y BAÑOS VARGAS',
    structure: 'phases',
    antes: [
      'Captura de pantalla 2026-07-30 080231.png',
      'Captura de pantalla 2026-07-30 080222.png',
      'Captura de pantalla 2026-07-30 080240.png',
    ],
    despues: [
      'WhatsApp Image 2026-07-30 at 7.51.37 AM.jpeg',
      'Captura de pantalla 2026-07-30 083254.png',
      'Captura de pantalla 2026-07-30 083149.png',
      'Captura de pantalla 2026-07-30 083159.png',
      'Captura de pantalla 2026-07-30 083225.png',
      'Captura de pantalla 2026-07-30 083214.png',
    ],
    durante: [
      'WhatsApp Image 2026-07-30 at 7.51.42 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.42 AM (2).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.42 AM (3).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.42 AM.jpeg',
      'Captura de pantalla 2025-12-26 143803.png',
      'Captura de pantalla 2025-12-26 140328.png',
    ],
  },
  {
    id: 'alfombras-zonas',
    pilar: 'Cultura y Bienestar',
    title: 'Modernización de alfombras en diferentes espacios',
    summary: 'Renovación integral de alfombras en oficinas, salas de reunión y espacios colaborativos, con una colorimetría diseñada según el carácter y uso de cada ambiente.',
    full: [
      'La modernización de diferentes espacios en Casa Vargas, Casa Bienestar, Casa Mejía y Casa Echavarría responde al propósito de consolidar un campus que acompañe la evolución del modelo educativo y organizacional del CESA.',
      'La intervención contempló la renovación integral de las alfombras en oficinas, espacios de trabajo colaborativo, salas de reunión, áreas de permanencia y ambientes administrativos. La propuesta de colorimetría fue diseñada de acuerdo con el carácter y uso de cada espacio, incorporando tonos que generan mayor calidez, dinamismo o concentración.',
      'Además de aportar una imagen más contemporánea, las nuevas alfombras mejoran el confort térmico y acústico, reducen el ruido ambiental e incrementan la sensación de bienestar en las actividades institucionales.',
    ],
    folder: 'MOD TAPETE DIFERENTES ZONAS',
    structure: 'phases',
    antes: [
      'WhatsApp Image 2026-07-30 at 7.51.31 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.31 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.32 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.32 AM (2).jpeg',
      'WhatsApp Image 2026-07-30 at 7.51.32 AM.jpeg',
    ],
    despues: [
      'WhatsApp Image 2026-07-30 at 8.58.27 AM (1).jpeg',
      'Captura de pantalla 2026-07-24 143740.png',
      'Captura de pantalla 2026-07-24 143656.png',
      'Captura de pantalla 2026-07-30 085430.png',
      'Captura de pantalla 2026-07-30 085418.png',
      'Captura de pantalla 2026-07-30 085451.png',
      'Captura de pantalla 2026-07-30 085441.png',
    ],
  },
  {
    id: 'exito-estudiantil',
    pilar: 'Cultura y Bienestar · Transformación Organizacional',
    title: 'Modernización oficina de Éxito Estudiantil',
    summary: 'Nuevo mobiliario ergonómico, revestimientos e iluminación para una atención más cercana, cálida y eficiente al acompañamiento de los estudiantes.',
    full: [
      'La modernización de la oficina de Éxito Estudiantil responde al propósito de fortalecer los espacios de atención que acompañan el desarrollo integral de los estudiantes, apoyando el bienestar, la permanencia y el acompañamiento continuo de la comunidad estudiantil.',
      'La intervención contempló la renovación integral del mobiliario, incorporando puestos de trabajo más funcionales y ergonómicos. Asimismo, se actualizaron los acabados interiores mediante nuevos revestimientos, iluminación y elementos arquitectónicos que proyectan una imagen institucional más contemporánea, acogedora y profesional.',
      'La renovación refleja el compromiso de la Iniciativa Campus CESA con la creación de ambientes que promueven el bienestar, la cercanía y una atención integral.',
    ],
    folder: 'OFICINA EXITO ESTUDIANTIL',
    structure: 'flatFiles',
    antes: ['ANTES.jpeg'],
    despues: ['DESPUES.png'],
  },
  {
    id: 'zona-lleras',
    pilar: 'Cultura y Bienestar',
    title: 'Adecuación zona de descanso Casa Lleras',
    summary: 'Una nueva Zona de Bienestar pensada para el descanso, la desconexión y la recuperación física y mental de estudiantes, docentes y colaboradores.',
    full: [
      'La creación de la nueva Zona de Bienestar de Casa Lleras responde al compromiso del Plan de Transformación de consolidar un campus centrado en las personas. Este espacio fue concebido para ofrecer un entorno destinado al descanso, la desconexión y la recuperación física y mental.',
      'La intervención contempló la adecuación de un ambiente con mobiliario ergonómico y confortable, acompañado de una propuesta de diseño interior basada en una paleta de colores que transmite calma, concentración y bienestar. La incorporación de iluminación arquitectónica y revestimientos contemporáneos crea un espacio acogedor e inspirador.',
      'La Zona de Bienestar de Casa Lleras fortalece el pilar de Cultura y Bienestar, reafirmando el compromiso institucional de crear espacios que promuevan el desarrollo integral de las personas.',
    ],
    folder: 'ZONA DE DESCANSO CASA LLERAS',
    structure: 'phases',
    antes: [
      'WhatsApp Image 2026-07-30 at 8.50.01 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 8.50.02 AM (1).jpeg',
      'WhatsApp Image 2026-07-30 at 8.50.02 AM.jpeg',
    ],
    despues: [
      'Captura de pantalla 2026-07-30 072002.png',
      'Captura de pantalla 2026-07-30 071925.png',
    ],
    durante: [
      'WhatsApp Image 2026-07-30 at 9.15.47 AM.jpeg',
      'WhatsApp Image 2026-07-30 at 8.50.02 AM (2).jpeg',
      'WhatsApp Image 2026-07-30 at 9.15.48 AM (1).jpeg',
    ],
  },
  {
    id: 'control-acceso',
    pilar: 'Smart Campus · Transformación Organizacional',
    title: 'Proyecto de control de acceso inteligente',
    summary: 'Cinco puntos de acceso con torniquetes inteligentes y reconocimiento facial, integrados con plataformas tecnológicas de control y monitoreo para un campus más seguro y ágil.',
    full: [
      'La implementación del nuevo sistema de control de acceso inteligente representa un avance en la consolidación de un Smart Campus. Este proyecto fortalece la seguridad institucional, optimiza la gestión de los accesos y mejora la experiencia de ingreso de estudiantes, docentes, colaboradores y demás públicos de interés.',
      'La intervención contempló la instalación de cinco puntos de acceso con torniquetes inteligentes equipados con tecnología de reconocimiento facial, complementados con puertas para personas con movilidad reducida, cerramientos en vidrio, sistemas de preregistro para visitantes y la integración con plataformas tecnológicas de control y monitoreo.',
      'El proyecto fortalece los pilares de Transformación Organizacional e Innovación, consolidando una infraestructura preparada para los retos de un campus inteligente, donde la tecnología se convierte en un habilitador de la seguridad, la eficiencia operativa y la experiencia institucional.',
    ],
    folder: 'CONTROL DE ACCESO',
    structure: 'gallery',
    images: [
      'Captura de pantalla 2026-07-30 072046.png',
      'Captura de pantalla 2026-05-08 081640.png',
      'Captura de pantalla 2026-05-08 081451.png',
    ],
  },
];
